/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List documents with pagination and filtering.
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /**
         * Create Document
         * @description Create a new document.
         *
         *     Side effects:
         *     - Enqueues gap_detection job (to be implemented in T-023)
         */
        post: operations["create_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document By Slug
         * @description Get a document by slug.
         */
        get: operations["get_document_by_slug_api_v1_documents_slug__slug__get"];
        /**
         * Update Document By Slug
         * @description Update a document by slug with pessimistic locking.
         *
         *     Side effects:
         *     - Creates automatic snapshot via middleware
         *     - Re-enqueues gap_detection job (to be implemented in T-023)
         */
        put: operations["update_document_by_slug_api_v1_documents_slug__slug__put"];
        post?: never;
        /**
         * Delete Document By Slug
         * @description Delete a document by slug.
         *
         *     Side effects:
         *     - CASCADE DELETE of gaps, document_snapshots
         *     - Cancels active related jobs (to be implemented in T-023)
         */
        delete: operations["delete_document_by_slug_api_v1_documents_slug__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Get a document by ID.
         */
        get: operations["get_document_api_v1_documents__document_id__get"];
        /**
         * Update Document
         * @description Update a document with pessimistic locking.
         *
         *     Side effects:
         *     - Creates automatic snapshot via middleware
         *     - Re-enqueues gap_detection job (to be implemented in T-023)
         */
        put: operations["update_document_api_v1_documents__document_id__put"];
        post?: never;
        /**
         * Delete Document
         * @description Delete a document.
         *
         *     Side effects:
         *     - CASCADE DELETE of gaps, document_snapshots
         *     - Cancels active related jobs (to be implemented in T-023)
         */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/slug/{slug}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Snapshots By Slug
         * @description Get snapshots for a document by slug.
         */
        get: operations["list_document_snapshots_by_slug_api_v1_documents_slug__slug__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Snapshots
         * @description Get snapshots for a document.
         */
        get: operations["list_document_snapshots_api_v1_documents__document_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/slug/{slug}/snapshots/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Snapshot By Slug
         * @description Restore a document snapshot by slug.
         *
         *     Side effects:
         *     - Creates snapshot of current state before restoring
         */
        post: operations["restore_snapshot_by_slug_api_v1_documents_slug__slug__snapshots__snapshot_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/snapshots/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Snapshot
         * @description Restore a document snapshot.
         *
         *     Side effects:
         *     - Creates snapshot of current state before restoring
         */
        post: operations["restore_snapshot_api_v1_documents__document_id__snapshots__snapshot_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return JWT access token.
         *
         *     Token expiration: 8 hours
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user and create personal organization.
         *
         *     Side effects:
         *     - Creates personal organization (is_personal=TRUE)
         *     - Hashes password with bcrypt
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gaps
         * @description List gaps with pagination and filtering.
         */
        get: operations["list_gaps_api_v1_gaps_get"];
        put?: never;
        /**
         * Create Gap
         * @description Create a new gap.
         */
        post: operations["create_gap_api_v1_gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gaps/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gap By Slug
         * @description Get a gap by slug.
         */
        get: operations["get_gap_by_slug_api_v1_gaps_slug__slug__get"];
        /**
         * Update Gap By Slug
         * @description Update a gap by slug (answer and status).
         */
        put: operations["update_gap_by_slug_api_v1_gaps_slug__slug__put"];
        post?: never;
        /**
         * Delete Gap By Slug
         * @description Delete a gap by slug.
         */
        delete: operations["delete_gap_by_slug_api_v1_gaps_slug__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gaps/{gap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gap
         * @description Get a gap by ID.
         */
        get: operations["get_gap_api_v1_gaps__gap_id__get"];
        /**
         * Update Gap
         * @description Update a gap (answer and status).
         */
        put: operations["update_gap_api_v1_gaps__gap_id__put"];
        post?: never;
        /**
         * Delete Gap
         * @description Delete a gap.
         */
        delete: operations["delete_gap_api_v1_gaps__gap_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description List proposals with pagination and filtering.
         */
        get: operations["list_proposals_api_v1_proposals_get"];
        put?: never;
        /**
         * Create Proposal
         * @description Create a new proposal.
         */
        post: operations["create_proposal_api_v1_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proposal
         * @description Get a proposal by ID.
         */
        get: operations["get_proposal_api_v1_proposals__proposal_id__get"];
        /**
         * Update Proposal
         * @description Update a proposal (status).
         */
        put: operations["update_proposal_api_v1_proposals__proposal_id__put"];
        post?: never;
        /**
         * Delete Proposal
         * @description Delete a proposal.
         */
        delete: operations["delete_proposal_api_v1_proposals__proposal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Comprehensive health check for all services.
         *
         *     Checks:
         *     - PostgreSQL: Database connection
         *     - Redis: Cache connection
         *     - Qdrant: Vector database connection
         *     - Ollama: LLM service connection via Tailscale
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Metrics
         * @description Get dashboard metrics including document, gap, and proposal statistics.
         *
         *     Calculates aggregated statistics directly from the database for efficiency.
         */
        get: operations["get_dashboard_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organizations
         * @description List organizations for the current user.
         *
         *     Returns all organizations where the user is the creator.
         */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /**
         * Create Organization
         * @description Create a new organization.
         *
         *     Side effects:
         *     - Creates organization with creator
         *     - Validates slug uniqueness
         */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization
         * @description Get a specific organization by ID.
         *
         *     Only returns organizations where the user is the creator.
         */
        get: operations["get_organization_api_v1_organizations__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List projects for the current user.
         *
         *     Returns all projects in organizations where the user is the creator.
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project.
         *
         *     Side effects:
         *     - Creates project within organization
         *     - Validates slug uniqueness within organization
         *     - Validates user is creator of organization
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get a specific project by ID.
         *
         *     Only returns projects in organizations where the user is the creator.
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DashboardMetricsResponse
         * @description Dashboard metrics response.
         */
        DashboardMetricsResponse: {
            /** @description Document statistics */
            documents: components["schemas"]["DocumentStats"];
            /** @description Gap statistics */
            gaps: components["schemas"]["GapStats"];
            /** @description Proposal statistics */
            proposals: components["schemas"]["ProposalStats"];
            /** @description Progress metrics */
            progress: components["schemas"]["ProgressMetrics"];
        };
        /**
         * DocumentCreate
         * @description Schema for creating a document.
         */
        DocumentCreate: {
            /**
             * Title
             * @description Document title
             */
            title: string;
            /**
             * Content
             * @description Document content (markdown)
             */
            content: string;
            /**
             * Filename
             * @description Document filename
             */
            filename: string;
        };
        /**
         * DocumentListItem
         * @description Schema for document list item (without full content).
         */
        DocumentListItem: {
            /**
             * Id
             * Format: uuid
             * @description Document ID
             */
            id: string;
            /**
             * Title
             * @description Document title
             */
            title: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Filename
             * @description Document filename
             */
            filename: string;
            /**
             * Rating
             * @description Document rating (0-10)
             */
            rating?: number | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * DocumentListResponse
         * @description Schema for paginated document list response.
         */
        DocumentListResponse: {
            /**
             * Items
             * @description List of documents
             */
            items: components["schemas"]["DocumentListItem"][];
            /**
             * Pagination
             * @description Pagination metadata
             */
            pagination: {
                [key: string]: unknown;
            };
        };
        /**
         * DocumentResponse
         * @description Schema for document response.
         */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             * @description Document ID
             */
            id: string;
            /**
             * Title
             * @description Document title
             */
            title: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Content
             * @description Document content (markdown)
             */
            content: string;
            /**
             * Filename
             * @description Document filename
             */
            filename: string;
            /**
             * Rating
             * @description Document rating (0-10)
             */
            rating?: number | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
            /**
             * Created By
             * @description Creator user ID
             */
            created_by?: string | null;
            /**
             * Updated By
             * @description Last updater user ID
             */
            updated_by?: string | null;
        };
        /**
         * DocumentStats
         * @description Document statistics.
         */
        DocumentStats: {
            /**
             * Total
             * @description Total number of documents
             */
            total: number;
            /**
             * Avgrating
             * @description Average document rating
             */
            avgRating?: number | null;
            /**
             * Healthy
             * @description Number of documents with rating >= 9
             */
            healthy: number;
            /**
             * Needsimprovement
             * @description Number of documents with rating < 9
             */
            needsImprovement: number;
            /**
             * Norating
             * @description Number of documents without rating
             */
            noRating: number;
        };
        /**
         * DocumentUpdate
         * @description Schema for updating a document.
         */
        DocumentUpdate: {
            /**
             * Title
             * @description Document title
             */
            title?: string | null;
            /**
             * Content
             * @description Document content (markdown)
             */
            content?: string | null;
            /**
             * Filename
             * @description Document filename
             */
            filename?: string | null;
        };
        /**
         * GapByPriority
         * @description Gap counts by priority.
         */
        GapByPriority: {
            /**
             * Critical
             * @description Number of critical gaps
             */
            critical: number;
            /**
             * High
             * @description Number of high priority gaps
             */
            high: number;
            /**
             * Medium
             * @description Number of medium priority gaps
             */
            medium: number;
            /**
             * Low
             * @description Number of low priority gaps
             */
            low: number;
        };
        /**
         * GapByStatus
         * @description Gap counts by status.
         */
        GapByStatus: {
            /**
             * Pending
             * @description Number of pending gaps
             */
            pending: number;
            /**
             * Responded
             * @description Number of responded gaps
             */
            responded: number;
            /**
             * Rejected
             * @description Number of rejected gaps
             */
            rejected: number;
        };
        /**
         * GapCreate
         * @description Schema for creating a gap.
         */
        GapCreate: {
            /**
             * Question
             * @description Gap question
             */
            question: string;
            /**
             * Priority
             * @description Gap priority level
             * @default medium
             */
            priority: string;
            /**
             * Context Missing
             * @description Context that is missing
             */
            context_missing?: string | null;
            /**
             * Role Affected
             * @description Role affected by this gap
             */
            role_affected?: string | null;
            /**
             * Document Id
             * Format: uuid
             * @description Document ID
             */
            document_id: string;
        };
        /**
         * GapListItem
         * @description Schema for gap list item.
         */
        GapListItem: {
            /**
             * Id
             * Format: uuid
             * @description Gap ID
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             * @description Document ID
             */
            document_id: string;
            /**
             * Slug
             * @description Gap slug
             */
            slug: string;
            /**
             * Question
             * @description Gap question
             */
            question: string;
            /**
             * Priority
             * @description Gap priority level
             */
            priority: string;
            /**
             * Status
             * @description Gap status
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * GapListResponse
         * @description Schema for paginated gap list response.
         */
        GapListResponse: {
            /**
             * Items
             * @description List of gaps
             */
            items: components["schemas"]["GapListItem"][];
            /**
             * Pagination
             * @description Pagination metadata
             */
            pagination: {
                [key: string]: unknown;
            };
        };
        /**
         * GapResponse
         * @description Schema for gap response.
         */
        GapResponse: {
            /**
             * Id
             * Format: uuid
             * @description Gap ID
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             * @description Document ID
             */
            document_id: string;
            /**
             * Slug
             * @description Gap slug
             */
            slug: string;
            /**
             * Question
             * @description Gap question
             */
            question: string;
            /**
             * Priority
             * @description Gap priority level
             */
            priority: string;
            /**
             * Status
             * @description Gap status
             */
            status: string;
            /**
             * Context Missing
             * @description Context that is missing
             */
            context_missing?: string | null;
            /**
             * Role Affected
             * @description Role affected by this gap
             */
            role_affected?: string | null;
            /**
             * Answer
             * @description Answer to the gap question
             */
            answer?: string | null;
            /**
             * Answered At
             * @description Timestamp when gap was answered
             */
            answered_at?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * GapStats
         * @description Gap statistics.
         */
        GapStats: {
            /**
             * Total
             * @description Total number of gaps
             */
            total: number;
            /** @description Gap counts by priority */
            byPriority: components["schemas"]["GapByPriority"];
            /** @description Gap counts by status */
            byStatus: components["schemas"]["GapByStatus"];
            /**
             * Pending
             * @description Number of pending gaps
             */
            pending: number;
        };
        /**
         * GapUpdate
         * @description Schema for updating a gap.
         */
        GapUpdate: {
            /**
             * Answer
             * @description Answer to the gap question
             */
            answer?: string | null;
            /**
             * Status
             * @description Gap status
             */
            status?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Health check response.
         */
        HealthCheckResponse: {
            /**
             * Status
             * @description Overall system status
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             * @description ISO 8601 timestamp of health check
             */
            timestamp: string;
            /**
             * Services
             * @description Status of individual services
             */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
        };
        /**
         * OrganizationCreate
         * @description Schema for creating an organization.
         */
        OrganizationCreate: {
            /**
             * Name
             * @description Organization name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Is Personal
             * @description Whether this is a personal organization
             * @default false
             */
            is_personal: boolean;
        };
        /**
         * OrganizationListItem
         * @description Schema for organization list item.
         */
        OrganizationListItem: {
            /**
             * Id
             * Format: uuid
             * @description Organization ID
             */
            id: string;
            /**
             * Name
             * @description Organization name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Is Personal
             * @description Whether this is a personal organization
             */
            is_personal: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * OrganizationResponse
         * @description Schema for organization response.
         */
        OrganizationResponse: {
            /**
             * Id
             * Format: uuid
             * @description Organization ID
             */
            id: string;
            /**
             * Name
             * @description Organization name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Is Personal
             * @description Whether this is a personal organization
             */
            is_personal: boolean;
            /**
             * Created By
             * Format: uuid
             * @description Creator user ID
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * ProgressMetrics
         * @description Progress metrics.
         */
        ProgressMetrics: {
            /**
             * Gapsresolvedpercentage
             * @description Percentage of gaps resolved
             */
            gapsResolvedPercentage: number;
            /**
             * Documentshealthypercentage
             * @description Percentage of healthy documents
             */
            documentsHealthyPercentage: number;
            /**
             * Avgresolutiontimehours
             * @description Average time to resolve gaps in hours
             */
            avgResolutionTimeHours?: number | null;
            /**
             * Proposalacceptancerate
             * @description Percentage of proposals implemented
             */
            proposalAcceptanceRate: number;
        };
        /**
         * ProjectCreate
         * @description Schema for creating a project.
         */
        ProjectCreate: {
            /**
             * Name
             * @description Project name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Description
             * @description Project description
             */
            description?: string | null;
            /**
             * Organization Id
             * Format: uuid
             * @description Organization ID
             */
            organization_id: string;
        };
        /**
         * ProjectListItem
         * @description Schema for project list item.
         */
        ProjectListItem: {
            /**
             * Id
             * Format: uuid
             * @description Project ID
             */
            id: string;
            /**
             * Name
             * @description Project name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Description
             * @description Project description
             */
            description: string | null;
            /**
             * Organization Id
             * Format: uuid
             * @description Organization ID
             */
            organization_id: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * ProjectResponse
         * @description Schema for project response.
         */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             * @description Project ID
             */
            id: string;
            /**
             * Name
             * @description Project name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe slug
             */
            slug: string;
            /**
             * Description
             * @description Project description
             */
            description: string | null;
            /**
             * Organization Id
             * Format: uuid
             * @description Organization ID
             */
            organization_id: string;
            /**
             * Created By
             * Format: uuid
             * @description Creator user ID
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * ProposalByStatus
         * @description Proposal counts by status.
         */
        ProposalByStatus: {
            /**
             * Pending
             * @description Number of pending proposals
             */
            pending: number;
            /**
             * Accepted
             * @description Number of accepted proposals
             */
            accepted: number;
            /**
             * Rejected
             * @description Number of rejected proposals
             */
            rejected: number;
            /**
             * Implemented
             * @description Number of implemented proposals
             */
            implemented: number;
        };
        /**
         * ProposalCreate
         * @description Schema for creating a proposal.
         */
        ProposalCreate: {
            /**
             * Name
             * @description Proposal name
             */
            name: string;
            /**
             * Description
             * @description Proposal description
             */
            description: string;
        };
        /**
         * ProposalListItem
         * @description Schema for proposal list item.
         */
        ProposalListItem: {
            /**
             * Id
             * Format: uuid
             * @description Proposal ID
             */
            id: string;
            /**
             * Slug
             * @description Proposal slug
             */
            slug: string;
            /**
             * Name
             * @description Proposal name
             */
            name: string;
            /**
             * Status
             * @description Proposal status
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * ProposalListResponse
         * @description Schema for paginated proposal list response.
         */
        ProposalListResponse: {
            /**
             * Items
             * @description List of proposals
             */
            items: components["schemas"]["ProposalListItem"][];
            /**
             * Total
             * @description Total number of proposals
             */
            total: number;
            /**
             * Page
             * @description Current page number
             * @default 1
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             * @default 25
             */
            per_page: number;
            /**
             * Total Pages
             * @description Total number of pages
             */
            total_pages: number;
        };
        /**
         * ProposalResponse
         * @description Schema for proposal response.
         */
        ProposalResponse: {
            /**
             * Id
             * Format: uuid
             * @description Proposal ID
             */
            id: string;
            /**
             * Slug
             * @description Proposal slug
             */
            slug: string;
            /**
             * Name
             * @description Proposal name
             */
            name: string;
            /**
             * Description
             * @description Proposal description
             */
            description: string;
            /**
             * Status
             * @description Proposal status
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * ProposalStats
         * @description Proposal statistics.
         */
        ProposalStats: {
            /**
             * Total
             * @description Total number of proposals
             */
            total: number;
            /** @description Proposal counts by status */
            byStatus: components["schemas"]["ProposalByStatus"];
            /**
             * Pending
             * @description Number of pending proposals
             */
            pending: number;
        };
        /**
         * ProposalUpdate
         * @description Schema for updating a proposal.
         */
        ProposalUpdate: {
            /**
             * Status
             * @description Proposal status
             */
            status?: string | null;
        };
        /**
         * ServiceStatus
         * @description Status of a single service.
         */
        ServiceStatus: {
            /**
             * Status
             * @description Service status: healthy, unhealthy, or unknown
             */
            status: string;
            /**
             * Message
             * @description Additional status message
             */
            message?: string | null;
        };
        /**
         * TokenResponse
         * @description Schema for JWT token response.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token expiration time in seconds
             */
            expires_in: number;
        };
        /**
         * UserCreate
         * @description Schema for creating a user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             * @description User email address
             */
            email: string;
            /**
             * Username
             * @description Username (alphanumeric + underscores)
             */
            username: string;
            /**
             * Password
             * @description User password
             */
            password: string;
        };
        /**
         * UserLogin
         * @description Schema for user login.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             * @description User email address
             */
            email: string;
            /**
             * Password
             * @description User password
             */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             * @description User ID
             */
            id: string;
            /**
             * Email
             * @description User email address
             */
            email: string;
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Is Active
             * @description User active status
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
                /** @description Filter by update date */
                updated_after?: string | null;
                /** @description Field to sort by */
                sort_by?: string;
                /** @description Sort order */
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_by_slug_api_v1_documents_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_by_slug_api_v1_documents_slug__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_by_slug_api_v1_documents_slug__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_api_v1_documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_snapshots_by_slug_api_v1_documents_slug__slug__snapshots_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_snapshots_api_v1_documents__document_id__snapshots_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_snapshot_by_slug_api_v1_documents_slug__slug__snapshots__snapshot_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_snapshot_api_v1_documents__document_id__snapshots__snapshot_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gaps_api_v1_gaps_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
                /** @description Filter by status */
                status?: string | null;
                /** @description Filter by priority */
                priority?: string | null;
                /** @description Filter by document */
                document_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gap_api_v1_gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_by_slug_api_v1_gaps_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gap_by_slug_api_v1_gaps_slug__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gap_by_slug_api_v1_gaps_slug__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_api_v1_gaps__gap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gap_api_v1_gaps__gap_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gap_api_v1_gaps__gap_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_v1_proposals_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
                /** @description Filter by status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_proposal_api_v1_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_v1_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_proposal_api_v1_proposals__proposal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_proposal_api_v1_proposals__proposal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    get_dashboard_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardMetricsResponse"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListItem"][];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
