"""add_missing_tables_and_columns

Revision ID: 071e1eea8aaa
Revises: a1b2c3d4
Create Date: 2026-06-04 06:15:37.990129

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "071e1eea8aaa"
down_revision: str | None = "a1b2c3d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.drop_index(op.f("ix_doc_rel_direction"), table_name="document_relationships")
    op.drop_index(op.f("ix_doc_rel_source"), table_name="document_relationships")
    op.drop_index(op.f("ix_doc_rel_target"), table_name="document_relationships")
    op.drop_index(op.f("ix_doc_rel_type"), table_name="document_relationships")
    op.drop_constraint(op.f("uq_doc_rel"), "document_relationships", type_="unique")
    op.add_column(
        "document_snapshots", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.drop_index(op.f("ix_snapshots_created_at"), table_name="document_snapshots")
    op.drop_index(op.f("ix_snapshots_document_id"), table_name="document_snapshots")
    op.drop_index(op.f("ix_documents_folder_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_project_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_rating"), table_name="documents")
    op.drop_index(op.f("ix_documents_vector_id"), table_name="documents")
    op.drop_constraint(
        op.f("uq_documents_folder_filename"), "documents", type_="unique"
    )
    op.create_index(
        "ix_documents_updated_at", "documents", ["updated_at"], unique=False
    )
    op.create_unique_constraint(None, "documents", ["vector_id"])
    op.drop_index(op.f("ix_folders_parent_folder_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_path"), table_name="folders")
    op.drop_index(op.f("ix_folders_project_id"), table_name="folders")
    op.drop_constraint(op.f("uq_folders_project_path"), "folders", type_="unique")
    op.add_column("gap_tags", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("gaps", sa.Column("context_missing", sa.Text(), nullable=True))
    op.add_column(
        "gaps", sa.Column("role_affected", sa.String(length=100), nullable=True)
    )
    op.drop_index(op.f("ix_gaps_document_id"), table_name="gaps")
    op.drop_index(op.f("ix_gaps_priority"), table_name="gaps")
    op.add_column("jobs", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_index(op.f("ix_jobs_entity"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_type"), table_name="jobs")
    op.drop_index(op.f("ix_organizations_created_by"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.add_column(
        "proposal_documents", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "proposal_gaps", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.drop_index(op.f("ix_proposals_status"), table_name="proposals")
    op.drop_index(
        op.f("ix_qdrant_collections_project"), table_name="qdrant_collections"
    )
    op.add_column(
        "question_document_references",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "question_gap_references",
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )
    op.drop_index(op.f("ix_questions_project_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_vector_id"), table_name="questions")
    op.create_unique_constraint(None, "questions", ["vector_id"])
    op.drop_index(op.f("ix_tags_project_id"), table_name="tags")
    op.drop_constraint(op.f("uq_tags_project_name"), "tags", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_sync_entity"), table_name="vector_sync_log")
    op.drop_index(op.f("ix_sync_status"), table_name="vector_sync_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sync_status"), "vector_sync_log", ["sync_status"], unique=False
    )
    op.create_index(
        op.f("ix_sync_entity"),
        "vector_sync_log",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("uq_tags_project_name"),
        "tags",
        ["project_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_tags_project_id"), "tags", ["project_id"], unique=False)
    op.drop_constraint(None, "questions", type_="unique")
    op.create_index(
        op.f("ix_questions_vector_id"), "questions", ["vector_id"], unique=True
    )
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_index(
        op.f("ix_questions_project_id"), "questions", ["project_id"], unique=False
    )
    op.drop_column("question_gap_references", "updated_at")
    op.drop_column("question_document_references", "updated_at")
    op.create_index(
        op.f("ix_qdrant_collections_project"),
        "qdrant_collections",
        ["project_id"],
        unique=False,
    )
    op.create_index(op.f("ix_proposals_status"), "proposals", ["status"], unique=False)
    op.drop_column("proposal_gaps", "updated_at")
    op.drop_column("proposal_documents", "updated_at")
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_created_by"),
        "organizations",
        ["created_by"],
        unique=False,
    )
    op.create_index(op.f("ix_jobs_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_jobs_entity"), "jobs", ["entity_type", "entity_id"], unique=False
    )
    op.drop_column("jobs", "updated_at")
    op.create_index(op.f("ix_gaps_priority"), "gaps", ["priority"], unique=False)
    op.create_index(op.f("ix_gaps_document_id"), "gaps", ["document_id"], unique=False)
    op.drop_column("gaps", "role_affected")
    op.drop_column("gaps", "context_missing")
    op.drop_column("gap_tags", "updated_at")
    op.create_unique_constraint(
        op.f("uq_folders_project_path"),
        "folders",
        ["project_id", "path"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_folders_project_id"), "folders", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_folders_path"), "folders", ["path"], unique=False)
    op.create_index(
        op.f("ix_folders_parent_folder_id"),
        "folders",
        ["parent_folder_id"],
        unique=False,
    )
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_index("ix_documents_updated_at", table_name="documents")
    op.create_unique_constraint(
        op.f("uq_documents_folder_filename"),
        "documents",
        ["folder_id", "filename"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_documents_vector_id"), "documents", ["vector_id"], unique=True
    )
    op.create_index(op.f("ix_documents_rating"), "documents", ["rating"], unique=False)
    op.create_index(
        op.f("ix_documents_project_id"), "documents", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_folder_id"), "documents", ["folder_id"], unique=False
    )
    op.create_index(
        op.f("ix_snapshots_document_id"),
        "document_snapshots",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_snapshots_created_at"),
        "document_snapshots",
        ["created_at"],
        unique=False,
    )
    op.drop_column("document_snapshots", "updated_at")
    op.create_unique_constraint(
        op.f("uq_doc_rel"),
        "document_relationships",
        ["source_document_id", "target_document_id", "relationship_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_doc_rel_type"),
        "document_relationships",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doc_rel_target"),
        "document_relationships",
        ["target_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doc_rel_source"),
        "document_relationships",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doc_rel_direction"),
        "document_relationships",
        ["direction"],
        unique=False,
    )
    op.drop_table("api_keys")
    # ### end Alembic commands ###
